# Generated by Django 4.2.27 on 2026-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'center_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CenterService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'center_services',
            },
        ),
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('recycling_center', 'Recycling Center'), ('collection_point', 'Collection Point')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('open_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recycling_centers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activity_locations',
                'ordering': ['-created_at'],
            },
        ),
    ]
