# Generated by Django 4.2.27 on 2026-01-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylocation',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centerservice',
            name='center',
            field=models.ForeignKey(db_column='center_id', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='map.recyclingcenter'),
        ),
        migrations.AddField(
            model_name='centerreview',
            name='center',
            field=models.ForeignKey(db_column='center_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='map.recyclingcenter'),
        ),
        migrations.AddField(
            model_name='centerreview',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='centerservice',
            unique_together={('center', 'service_name')},
        ),
        migrations.AlterUniqueTogether(
            name='centerreview',
            unique_together={('center', 'user')},
        ),
    ]
