# Generated by Django 4.2.27 on 2026-01-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposalreport',
            name='provider',
            field=models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_waste_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disposalreport',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
