# Generated by Django 4.2.27 on 2026-01-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#10B981', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='RecycleTrack Team', max_length=100)),
                ('reading_time', models.PositiveIntegerField(help_text='Estimated reading time in minutes')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='education/images/')),
                ('excerpt', models.TextField(help_text='Short summary for the card view')),
                ('content', models.TextField(help_text='Main content in Markdown format')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='education.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
