# Generated by Django 4.2.27 on 2026-02-17 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(help_text='The ID from the YouTube URL (e.g., dQw4w9WgXcQ)', max_length=50)),
                ('channel', models.CharField(help_text='Name of the YouTube channel', max_length=100)),
                ('duration', models.CharField(help_text='Format: MM:SS (e.g., 10:15)', max_length=10)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='education.category')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
