# Generated by Django 4.2.16 on 2026-02-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(help_text='Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)', max_length=200),
        ),
    ]
