# Generated by Django 5.2.8 on 2025-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'badges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('activity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'points_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('user_badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_badges',
                'managed': False,
            },
        ),
    ]
