# Generated by Django 4.2.27 on 2026-01-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleuser',
            name='badge',
            field=models.CharField(default='Newcomer', max_length=50),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
