# Generated by Django 4.2.27 on 2026-01-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recycleuser_badge_alter_recycleuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclinglog',
            name='quantity',
            field=models.CharField(default='1 bag', max_length=50),
        ),
        migrations.AddField(
            model_name='recyclinglog',
            name='waste_type',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Glass', 'Glass'), ('Paper', 'Paper'), ('Metal', 'Metal'), ('Electronics', 'Electronics')], default='Plastic', max_length=50),
        ),
    ]
