# Generated by Django 4.2.27 on 2026-01-24 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recyclinglog_quantity_recyclinglog_waste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('Glass', 'Glass'), ('Paper', 'Paper'), ('Metal', 'Metal'), ('Electronics', 'Electronics')], max_length=50)),
                ('quantity', models.CharField(default='1 bag', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Pickup'), ('verified', 'Verified & Points Awarded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pickup_requests',
            },
        ),
    ]
