# Generated by Django 4.2.27 on 2026-01-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pickuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Pickup'), ('verified', 'Verified & Points Awarded'), ('cancelled', 'Cancelled / Rejected')], default='pending', max_length=20),
        ),
    ]
