# Generated by Django 4.2.27 on 2026-01-26 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pickuprequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='collector',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'service_provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Pickup'), ('assigned', 'Assigned to Collector'), ('collected', 'Waste Collected'), ('verified', 'Verified & Points Awarded'), ('cancelled', 'Cancelled / Rejected')], default='pending', max_length=20),
        ),
    ]
