# Generated by Django 4.2.27 on 2026-01-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('waste', '0002_alter_disposalreport_provider_and_more'),
        ('users', '0006_pickuprequest_collector_alter_pickuprequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted_waste_types', models.CharField(default='Plastic, Paper, Glass, Metal', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='recycleuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='center_name',
        ),
        migrations.RemoveField(
            model_name='recycleuser',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('collected', 'Collected'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='waste_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='recyclinglog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recyclinglog',
            name='points_awarded',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recyclinglog',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recyclinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recyclinglog',
            name='waste_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='pickuprequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recycleuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recyclinglog',
            table=None,
        ),
        migrations.DeleteModel(
            name='AdminLog',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='users.recyclingcenter'),
        ),
    ]
