# Generated by Django 4.2.27 on 2026-01-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('users', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleuser',
            name='latitude',
            field=models.FloatField(default=-1.2921),
        ),
        migrations.AddField(
            model_name='recycleuser',
            name='longitude',
            field=models.FloatField(default=36.8219),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
