# Generated by Django 4.2.27 on 2026-01-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('users', '0009_recycleuser_latitude_recycleuser_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_address',
            field=models.CharField(blank=True, help_text='Street or Landmark', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='region',
            field=models.CharField(blank=True, help_text='Estate or Area', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='recycleuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission'),
        ),
    ]
