# Generated by Django 4.2.27 on 2026-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pickuprequest_latitude_pickuprequest_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
