# Generated by Django 4.2.27 on 2026-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_pickuprequest_rating_pickuprequest_review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycleuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
