# Generated by Django 4.2.27 on 2026-02-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='actual_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='billed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
